// <auto-generated />
namespace Fitnessclub_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateTrainer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTrainer));
        
        string IMigrationMetadata.Id
        {
            get { return "202011170003055_updateTrainer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
